# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only

#### KUBERNETES DOCKER-REGISTRY SECRET CREATION START ####
- name: Create Docker Registry secret
  command: kubectl create secret docker-registry "{{ kube_docker_registry_secret_name }}" --docker-server="{{ kube_docker_registry_server }}" --docker-username="{{ kube_docker_registry_username }}" --docker-password="{{ kube_docker_registry_pwd }}" --docker-email="{{ kube_docker_registry_email }}"
  ignore_errors: true
  when: "{{ kube_docker_registry_secret_name }}"
  tags:
    - deploy_apps_in_kube
#### KUBERNETES DOCKER-REGISTRY SECRET CREATION END ####

#### PROVISION APP TO KUBERNETES START ####
# TODO: This needs to be updated to support more than just Kubernetes application files.
#       Ultimately more than just this playbook will use the file input type and we need
#       to support those also. Copying the entire prepare folder is a stopgap until the
#       Python logic changes can be made to support placing the Kubernetes app files in
#       their own location.
- name: Copy files to Kubernetes master
  copy:
    src: "/var/lib/chaperone/prepare"
    dest: "/tmp"
  tags:
    - deploy_apps_in_kube

- name: Get the list of files
  command: find /tmp/prepare -type f -printf "%f\n"
  register: kube_app_files
  tags:
    - deploy_apps_in_kube

- name: Echo the file list
  debug:
    msg: "{{ kube_app_files.stdout_lines }}"
  tags:
    - deploy_apps_in_kube

- name: Provision the apps
  command: kubectl create -f "{{ item }}"
  args:
    chdir: "/tmp/prepare"
  with_items:
    - "{{ kube_app_files.stdout_lines }}"
  tags:
    - deploy_apps_in_kube
#### PROVISION APP TO KUBERNETES END ####

#### DESTROY APPS IN KUBERNETES START ####
- name: Destroy the apps
  command: kubectl delete -f "{{ item }}"
  args:
    chdir: "/root/prepare"
  with_items:
    - "{{ kube_app_files.stdout_lines }}"
  tags:
    - destroy_apps_in_kube
#### DESTROY APPS IN KUBERNETES END ####
