# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
#### CLEANUP START ####
- name: Disable kube-addons service
  service: 
    name: kube-addons
    enable: no 
    state: stopped
  ignore_errors: true
  tags:
    - kube_reset_installation
    
- name: Detemine if kubectl is installed
  stat:
    path: /usr/bin/kubectl
  register: kubectl_exists
  tags:
    - kube_reset_installation
    
- name: Remove any existing Kube objects
  command: kubectl delete deployments,svc,rc,pods,nodes --all
  when: kubectl_exists.stat.exists
  tags:
    - kube_reset_installation
    
- name: Remove any existing hidden Kube objects
  command: kubectl delete deployments,svc,rc,pods --all --namespace=kube-system
  when: kubectl_exists.stat.exists
  tags:
    - kube_reset_installation
  
- name: Clean out any existing etcd keys and remove docker0 bridge
  command: "{{ item }}"
  ignore_errors: true
  with_items:
    - etcdctl rm /registry --recursive
    - etcdctl rm /coreos.com/network --recursive
    - /usr/sbin/ifconfig docker0 down
    - /usr/sbin/brctl delbr docker0
  tags:
    - kube_reset_installation
    
- name: Remove existing addons and manifests
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kube_addons_dir }}" 
    - "{{ kube_addons_token_dir }}"
    - "{{ kubelet_manifests_dir }}"
  when: kubectl_exists.stat.exists
  tags:
    - kube_reset_installation
#### CLEANUP END ####

#### SERVICE SHUTDOWN START ####
- name: Shutdown and disable Kubernetes minion services
  service: 
    name: "{{ item }}"
    enabled: no 
    state: stopped
  with_items:
    - kubelet
    - kube-proxy
    - docker
    - flannel
  when: kubectl_exists.stat.exists
  ignore_errors: true
  tags:
    - kube_reset_installation
    
- name: Shutdown and disable Kubernetes master services
  service: 
    name: "{{ item }}"
    enabled: no 
    state: stopped
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
    - docker
    - flannel
  when: kubectl_exists.stat.exists
  ignore_errors: true
  tags:
    - kube_reset_installation
#### SERVICE SHUTDOWN END ####
