# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    name: mysqldb
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    name: mysqldb
