# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: go-reminders
  name: go-reminders
spec: 
  ports:
    # the port that this service should serve on
    - port: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: go-reminders
  type: NodePort
